---
run:
  timeout: 10m

issues:
  skip-dirs:
    - gen
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - revive
    - lll
    - interfacer
    - scopelint
    - maligned
    - golint
    - gofmt
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - funlen
    - exhaustivestruct
    - tagliatelle
    - godox
    - ireturn

    # We should strive to enable these:
    - testpackage
    - stylecheck
    - wrapcheck
    - paralleltest
    - nlreturn
    - ifshort
    - gomnd
    - goerr113
    - errorlint
    - forcetypeassert
    - errname
    - wsl
    - unparam
    - makezero
    - gosec
    - gocritic
    - forbidigo
    - dupl
    - goconst
    - unconvert
    - exhaustive
    - varnamelen
    - nilnil

    # We might want to enable this, but it might be a lot of work
    - cyclop
    - nestif
