---
run:
  timeout: 10m

issues:
  skip-dirs:
    - gen
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - revive
    - lll
    - interfacer
    - scopelint
    - maligned
    - golint
    - gofmt
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - funlen
    - exhaustivestruct
    - tagliatelle
    - godox
    - ireturn

    # In progress
    - gocritic

    # TODO: approve: ok, db, id
    - varnamelen

    # We should strive to enable these:
    - testpackage
    - stylecheck
    - wrapcheck
    - goerr113
    - errorlint
    - forcetypeassert
    - errname
    - gosec
    - forbidigo
    - dupl
    - makezero
    - paralleltest

    # We might want to enable this, but it might be a lot of work
    - cyclop
    - nestif
    - wsl # might be incompatible with gofumpt
