---
run:
  timeout: 10m

issues:
  skip-dirs:
    - gen
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - revive
    - lll
    - interfacer
    - scopelint
    - maligned
    - golint
    - gofmt
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - funlen
    - exhaustivestruct
    - tagliatelle
    - godox
    - ireturn

    # In progress
    - gocritic

    # We should strive to enable these:
    - wrapcheck
    - goerr113
    - forcetypeassert
    - gosec
    - forbidigo
    - dupl
    - makezero
    - paralleltest

    # We might want to enable this, but it might be a lot of work
    - cyclop
    - nestif
    - wsl # might be incompatible with gofumpt
    - testpackage

linters-settings:
  varnamelen:
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-names:
      - err
      - db
      - id
      - ip
      - ok
      - c
